/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  category: () => import("@/views/category/index.vue"),
  drug: () => import("@/views/drug/index.vue"),
  "expiry-alert": () => import("@/views/expiry-alert/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "inventory-log": () => import("@/views/inventory-log/index.vue"),
  inventory: () => import("@/views/inventory/index.vue"),
  "operation-log": () => import("@/views/operation-log/index.vue"),
  "purchase-order": () => import("@/views/purchase-order/index.vue"),
  sale: () => import("@/views/sale/index.vue"),
  supplier: () => import("@/views/supplier/index.vue"),
  "user-manage": () => import("@/views/user-manage/index.vue"),
};
